### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by soumyaDghosh** [hyttmi/howdy-unlock-keyring#1]
I setup the script as u said yet getting error.

running your script manually via python, I get

````
 soumyaxubuntu  soumyas-GF63-Thin-11UC  ~  python3 /home/soumyaxubuntu/.config/unlock.py
failed to connect socket `/run/user/1000/.ydotool_socket': No such file or directory
Please check if ydotoold is running.
failed to connect socket `/run/user/1000/.ydotool_socket': No such file or directory
Please check if ydotoold is running.
````

ydotool status

````
 soumyaxubuntu  soumyas-GF63-Thin-11UC  ~  service ydotool status
● ydotool.service - Starts ydotoold service
     Loaded: loaded (/etc/systemd/system/ydotool.service; enabled; preset: enabled)
     Active: active (running) since Tue 2023-01-17 21:03:06 IST; 12min ago
   Main PID: 52524 (ydotoold)
      Tasks: 1 (limit: 9084)
     Memory: 192.0K
        CPU: 1ms
     CGroup: /system.slice/ydotool.service
             └─52524 /usr/local/bin/ydotoold

Jan 17 21:03:06 soumyas-GF63-Thin-11UC systemd[1]: Started Starts ydotoold service.

`````

Startup script

````
[Desktop Entry]
Type=Application
Exec=python3 /home/soumyaxubuntu/.config/unlock.py
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_US]=unlock keyring
Name=unlock keyring
Comment[en_US]=
Comment=
`````

**Comment by hyttmi** [comment]
Can you run ydotool command manually when the systemd service is running? For example:

```ydotool key 28:1 28:0```

**Comment by soumyaDghosh** [comment]
No it's not

**Comment by soumyaDghosh** [comment]
I have perfectly installed ydotool, ig. Can you describe the process?

**Comment by hyttmi** [comment]
Would be helpful if you could show me what happens when you try the command which I posted above.

**Comment by soumyaDghosh** [comment]
wait

**Comment by soumyaDghosh** [comment]
```````` 
soumyaxubuntu  soumyas-GF63-Thin-11UC  ~  ydotool key 28:1 28:0
failed to connect socket `/run/user/1000/.ydotool_socket': No such file or directory
Please check if ydotoold is running.

**Comment by soumyaDghosh** [comment]
![image](https://user-images.githubusercontent.com/72045785/212975823-17ff38a0-b989-482b-92b8-558ba4016511.png)

**Comment by hyttmi** [comment]
Looks more like ydotool issue to me. I will try to reproduce this issue tomorrow and will get back to you.

**Comment by soumyaDghosh** [comment]
Thanks a lot. BTW another question, do u use a laptop, if yes, an MSI laptop?

**Comment by hyttmi** [comment]
The issue is in ydotool probably:

https://github.com/ReimuNotMoe/ydotool

And yes, I have a laptop but it's Asus.

**Comment by soumyaDghosh** [comment]
Can you point out the issue please

**Comment by hyttmi** [comment]
> Can you point out the issue please

Well, ydotool does work when you run it with sudo, so it's probably some type of permission issue. Unfortunately I didn't have time to fix the issue but will address it on somepoint and update README.

**Comment by soumyaDghosh** [comment]
You use sudo in this python programe? Is there really any need for that?

**Comment by hyttmi** [comment]
> You use sudo in this python programe? Is there really any need for that?

Nope, I just tested ydotool command with sudo and it works.

**Comment by soumyaDghosh** [comment]
> > You use sudo in this python programe? Is there really any need for that?
> 
> Nope, I just tested ydotool command with sudo and it works.

Ooooo sorry, wrong intepretation

**Comment by soumyaDghosh** [comment]
https://github.com/ReimuNotMoe/ydotool/issues/32
This may help
